#!/usr/bin/env ruby
# -*- mode: ruby; -*-
# vi: set ft=ruby :

require 'fileutils'
require 'json'
require 'yaml'

class String
  %w{black red green yellow blue magenta cyan white}.each_with_index do |colour, index|
    define_method "#{colour}" do
      return "\e[3#{index}m#{self}\e[0m"
    end
    define_method "#{colour}_bkg" do
      return "\e[4#{index}m#{self}\e[0m"
    end
  end

  def bold;           "\e[1m#{self}\e[22m" end
  def italic;         "\e[3m#{self}\e[23m" end
  def underline;      "\e[4m#{self}\e[24m" end
  def blink;          "\e[5m#{self}\e[25m" end
  def reverse_colour; "\e[7m#{self}\e[27m" end

end



module Command

  def substitute subs, pwd
    raise 'Function `substitute` not implemented'
  end

  def execute
    raise 'Function `execute` not implemented'
  end

  def cleanup
    # Most `Command` instances will not need to do anything to cleanup
  end

private
  def substitute_for string, subs, pwd
    subs.each do |key, val|
      next if key == 'pwd' # ignore pwd if it is added by mistake
      string = string.gsub(/\$\{#{key}\}/, (val || key))
    end
    string = string.gsub(/\$\{pwd\}/, pwd)
  end

end



class FileRemover
  include Command

  def initialize(file)
    @file = file
  end

  def substitute subs, pwd
    @file = substitute_for(@file, subs, pwd)
  end

  def execute
    begin
      FileUtils.rm_rf @file
      return true
    rescue Errno::ENOENT
      return false
    end
  end

  def to_s
    "rm -Rf #{@file}"
  end

end

class Extractor
  include Command

  def initialize(src_path, dst_path)
    @src_path = src_path
    @dst_path = dst_path
  end

  def substitute subs, pwd
  end

  def execute
    puts "Extracting '#{@src_path}' into '#{@dst_path}'"
    if !Dir.exist?(@dst_path) || Dir.empty?(@dst_path)
      Dir.mkdir(@dst_path) if !Dir.exist?(@dst_path)
      puts %x{ tar -zxf \"#{@src_path}\" -C \"#{@dst_path}\" }
      result = $?.exited? && ($?.exitstatus == 0)
      return result
    end

    puts "Archive previously extracted to '#{@dst_path}'"
    return true
  end

end

class CloneCommand
  include Command

  attr_reader :repository

  def initialize(repository, path)
    @repository = repository
    @path = path
  end

  def substitute subs, pwd
  end

  def execute
    /^.+\/([^\.]+)\.git$/.match(@repository)
    if !Dir.exist?(@path)
      puts "Cloning '#{@repository}' into '#{@path}'"
      puts %x{ git clone \"#{@repository}\" \"#{@path}\" }
      result = $?.exited? && ($?.exitstatus == 0)
      return result
    end
    
    puts "Repository '#{@repository}' previously cloned into '#{@path}'"
    Dir.chdir(@path) do
      puts %x{ git status }
      result = $?.exited? && ($?.exitstatus == 0)
      return result if !result
      puts %x{ git pull }
      result = $?.exited? && ($?.exitstatus == 0)
      return result
    end
  end

end

class EnvVar
  include Command

  def initialize(name, value)
    @name = name
    @original = ENV[@name]
    @value = value
  end

  def substitute subs, pwd
    @value = substitute_for(@value, subs, pwd)
  end

  def execute
    ENV[@name] = @value
    return true
  end

  def cleanup
    ENV[@name] = @original
    return true
  end

  def to_s
    "ENV[#{@name}] == #{@value}"
  end

  def self.from_h hash
    if hash['type'] == 'EnvVar'
      return EnvVar.new(hash['key'], hash['value'])
    end
    return nil
  end

end

class Environment
  include Command

  def initialize(hash)
    @hash = hash
    @subs = hash.clone
    @original = @hash.filter_map {|key, val| [ key, ENV[key] ] if ENV.key?(key) }.to_h
  end

  def substitute subs, pwd
    @subs = @hash.transform_values{|val| substitute_for(val, subs, pwd) }
  end

  def execute
    @subs.each{|key, val| ENV[key] = val }
    return true
  end

  def cleanup
    @original.each{|key, val| ENV[key] = val }
    (@subs.keys - @original.keys).each{|key| ENV[key] = nil }
    return true
  end

  def to_s
    "ENV[ #{@subs.map{|key, val| "#{key} <= \"#{val}\"" }.join(', ')} ]"
  end

  def self.from_h hash
    if hash['type'] == 'Environment'
      return Environment.new(hash['data'])
    end
    return nil
  end

end


class CommandExecutor
  include Command

  COMMAND_SET = [ EnvVar, Environment, CommandExecutor ]

  attr_reader :dir, :subs
  
  def initialize(dir, commands, environment, subs = {})
    @dir = dir
    @commands = commands
    @executed = []
    @environment = Environment.new(environment)
    @subs = subs
  end

  def substitute subs, pwd
    @dir = substitute_for(@dir, subs, pwd)
    @subs = subs
  end

  def execute
    Dir.chdir(@dir) do
      @environment.execute

      @commands.each do |cmd|
        pwd = Dir.pwd
        if cmd.is_a? String
          return false if !self.execute_direct(cmd, pwd)
        elsif cmd.is_a? Hash
          command = COMMAND_SET.map {|type| type.from_h cmd } .select {|s| !s.nil?} .first
          puts "#{'FAILED'.red} :: #{cmd.yellow}" if command.nil?
          return false if command.nil?

          @executed << command
          return false if !self.execute_command(command, pwd)
        elsif cmd.is_a? Command
          @executed << cmd
          return fale if !self.execute_command(cmd, pwd)
        elsif cmd.is_a? Proc
          return false if !self.execute_proc(cmd, pwd)
        end
      end
    end
  
    return true
  end

  def cleanup
    @executed.each{|command| command.cleanup }
    @environment.cleanup
  end

  def to_s
    "cd #{@dir} => [ #{@commands[0].length > 20 ? @commands[0][0..20] : @commands[0]} ... ]"
  end

  def self.from_h hash
    if hash['type'] == 'CommandList'
      # path = "#{Dir.pwd}/#{hash['rel_path']}" || "#{hash['abs_path']}"
      return CommandExecutor.new(hash['rel_path'], hash['commands'], {})
    end
    return nil
  end

private
  def execute_direct cmd, pwd
    cmd = substitute_for(cmd, @subs, pwd)
    puts "Executing: #{cmd.yellow}"
    puts %x{ #{cmd} }
    result = $?.exited? && ($?.exitstatus == 0)
    if !result then
      puts "#{'FAILED'.red} :: #{cmd.yellow}"
    end
    return result
  end

  def execute_command cmd, pwd
    cmd.substitute(@subs, pwd)
    puts "Executing: #{cmd.to_s.yellow}"
    result = cmd.execute
    if !result then
      puts "#{'FAILED'.red} :: #{cmd.to_s.yellow}"
    end
    return result
  end

  def execute_proc proc, pwd
    puts "Executing: #{'Inline Procedure'.yellow}"
    result = cmd.call
    if !result then
      puts "#{'FAILED'.red} :: #{'Inline Procedure'.yellow}"
    end
    return result
  end

end



class Flags
  attr_reader :platform
  attr_reader :path
  attr_reader :clean_flag
  attr_reader :ensure_upstream
  attr_reader :ensure_downstream
  attr_reader :build_flag
  attr_reader :libraries
  attr_reader :help_flag
  attr_reader :verbose_flag

  def initialize(arguments)
    @platform = ''
    @path = Dir.pwd
    @clean_flag = false
    @ensure_upstream = false
    @ensure_downstream = false
    @build_flag = true
    @libraries = []
    @help_flag = false
    @verbose_flag = false

    arguments.each do |item|
      case item
      when '--clean'
        @clean_flag = true
      when '--upstream'
        @ensure_upstream = true
      when '--downstream'
        @ensure_downstream = true
      when /--platform=(.*)/
        @platform = $1.lstrip.rstrip
      when /-p=(.*)/
        @platform = $1.lstrip.rstrip
      when /--path=(.*)/
        @path = $1.lstrip.rstrip
      when '--help'
        @help_flag = true
      when '--verbose'
        @verbose_flag = true
      when '-v'
        @verbose_flag = true
      else
        @libraries << item
      end
    end
  end

  def has_platform?
    return !self.platform.nil? && !self.platform.empty?
  end

  def print_tasks
    puts 'Build Dependencies Tasks:'
    puts '--help - Print this message'
    puts '--platform=<platform> or -p=<platform> - Use <platform> for the dependency build [required]'
    puts '--path=<directory> - Use <directory> as the location of the properties and dependencies'
    puts '--clean - Clean the build directories'
    puts '--upstream - Ensure upstream libraries are built before building selected libraries'
    puts '--downstream - Ensure downstream libraries are built after building selected libraries'
    puts '<library> - Build the specified dependency library and its downstream libraries'
    puts '--verbose or -v - Enable verbose output'
    exit!(-1)
  end
    
end

module DependencyKind
  OTHER = 0
  REPOSITORY = 1
  ARCHIIVE = 2
end

class Dependency
  attr_reader :target
  attr_reader :path, :output
  attr_reader :depends
  attr_reader :kind
  attr_reader :repository, :archive
  attr_reader :environment
  attr_reader :clean, :build
  attr_accessor :built

  attr_reader :working

  def initialize target, configuration
    @target = target
    @path = configuration['path']
    @output = configuration['output']
    @depends = configuration['depends'] || []
    @kind = !configuration['repository'].nil? ? DependencyKind::REPOSITORY : (!configuration['archive'].nil? ? DependencyKind::ARCHIIVE : DependencyKind::OTHER)
    @repository = configuration['repository']
    @archive = configuration['archive']
    @environment = configuration['environment'] || {}
    @clean = configuration['clean'] || []
    @build = configuration['build'] || []
    self.built = false

    @working = "#{Dir.pwd}/#{self.path || self.target}"
  end

  def get_path
    return self.path || self.target
  end

  def is_valid?
    return !self.target.nil? && !self.output.nil? && (self.repository.nil? || self.archive.nil?)
  end

  def is_target? target
    return true if (self.target == target) || (self.path == target)
    false
  end

  def get_downstream dependency_map
    dependency_map.filter_map{|target, dependency| [ target, dependency ] if (self.target != target) && dependency.depends.include?(self.target) }.to_h
  end

  def get_downstream_targets dependency_map
    dependency_map.filter_map{|target, dependency| target if (self.target != target) && dependency.depends.include?(self.target) }
  end

  def get_upstream dependency_map
    dependency_map.filter_map{|target, dependency| [ target, dependency ] if (self.target != target) && self.depends.include?(target) }.to_h
  end

  def get_upstream_targets dependency_map
    self.depends
  end

  def get_working
    return "#{self.working}#{self.archive_name}"
  end

  def get_output
    return "#{self.working}#{self.archive_name}/#{self.output}"
  end

  def obtain system_dir
    if self.repository
      result = CloneCommand.new(self.repository, self.working).execute
      puts "#{'ERROR'.red} Failed to clone repository #{self.repository.cyan}" if !result
      return false if !result
    elsif self.archive
      src_path = self.archive_src_path system_dir
      dst_path = self.archvie_dst_path

      result = Extractor.new(src_path, dst_path).execute
      puts "#{'ERROR'.red} Failed to extract archive #{src_path.cyan} at #{dst_path.magenta}" if !result
      return false if !result
    else
      if !Dir.exist?(self.working)
        puts "Creating working directory #{self.working.cyan}"
        Dir.mkdir(self.working)
      end
    end

    return true
  end

private
  def archive_name
    if self.archive.is_a?(String)
      return "/#{self.get_path}"
    end
    if self.archive.is_a?(Hash)
      return "/#{self.archive['name']}"
    end
    return ''
  end
  
  def archive_src_path system_dir
    if self.archive.is_a?(String)
      return "#{system_dir}/#{"#{self.archive}/" || ''}#{self.get_path}.tar.gz"
    elsif self.archive.is_a?(Hash)
      return "#{system_dir}/#{self.archive['path'] || ''}/#{self.archive['name']}.#{self.archive['extension'] || 'tar.gz'}"
    end
    return nil
  end

  def archvie_dst_path
    return "#{@working}"
  end

end

class DependencyBuilder
  def initialize flags
    @dependency_map, @filename = DependencyBuilder.load_properties(flags)
    @before_each = @dependency_map['--before-each']
    @after_each = @dependency_map['--after-each']
    @dependency_map = @dependency_map.filter_map{|key, val| [ key, Dependency.new(key, val) ] unless (key == '--before-each') || (key == '--after-each') }.to_h
    @flags = flags
    @system_dir = Dir.pwd

    @subs = @dependency_map.transform_values{|val| val.get_working }
    @subs.update(@dependency_map.filter_map{|key, val| [ "#{key}::path", "#{val.get_path}" ] unless (key == '--before-each') || (key == '--after-each') }.to_h)
    @subs.update(@dependency_map.filter_map{|key, val| [ "#{key}::output", "#{val.get_output}" ] unless (key == '--before-each') || (key == '--after-each') }.to_h)
  end

  def build_single target
    return build_list([ target ])
  end

  def build_all
    return build_list(@dependency_map.keys)
  end

  def build_list targets
    result = build_multiple_targets targets
    built_list = @dependency_map.filter_map{|target, dependency| target if dependency.built }
    puts '', "Built Dependencies: #{built_list.join(', ')}" unless built_list.empty?
    return result
  end

private
  def build_single_target target, upstream_override
    return true if target == '--before-each' || target == '--after-each'

    # If we are provided with a path then find a matching target key entry for that path
    configuration = @dependency_map.filter_map {|_, dependency| dependency if dependency.is_target?(target) }.first
    if configuration.nil? then
      puts "#{'FAILED'.red} :: No such dependency `#{target.yellow}` or path to dependency"
      return false
    end
    puts "Building Dependency #{configuration.target.cyan} from given path #{target.magenta}" if target == configuration.path

    if !configuration.is_valid? then
      if configuration.repository && configuration.archive then
        puts "#{'ERROR'.red} Configuration for #{configuration.target.yellow} cannot have repository and archive fields" if !result
        return false
      else
        puts "#{'FAILED'.red} :: configuration for #{configuraiton.target.yellow} is not valid"
      end
      return false
    end

    return false unless build_multiple_targets(configuration.get_upstream_targets(@dependency_map), upstream_override) if @flags.ensure_upstream || upstream_override
    
    puts "Target #{configuration.target} already built" if configuration.built && @flags.verbose_flag
    return true if configuration.built

    puts "Assembling dependency: #{configuration.target.cyan}"
    puts "Working Directory: #{configuration.get_working.yellow}" if @flags.verbose_flag
    puts "Output Directory: #{configuration.get_output.yellow}" if @flags.verbose_flag
    result = false

    if Dir.exist?(configuration.get_output) && !@flags.clean_flag
      puts "Output directory #{configuration.get_output} exists for target #{configuration.target}" if @flags.verbose_flag
      puts "#{'SUCCESS:'.blue} :: #{configuration.target.cyan} :: #{configuration.get_output}"
      configuration.built = true
      return true
    end

    subs = @subs.clone()
    subs.each{|key, val| puts "SUB `#{key}` :: `#{val}`"}
    subs['output'] = configuration.get_output
    subs['pwd'] = configuration.get_working
    subs['system'] = @system_dir
    subs['self'] = @filename

    return false if !configuration.obtain @system_dir

    environment = configuration.environment

    puts "PWD: #{configuration.get_working}"
    puts "DST: #{configuration.get_output}"

    if @before_each && !@before_each.empty?
      puts "Before Each: #{target.cyan}"
      result = CommandExecutor.new(configuration.get_working, @before_each, environment, subs).execute
      puts "#{'ERROR:'.red} Before each build commands for #{target.cyan} returned #{'false'.magenta}" if !result && @flags.verbose_flag
      return false unless result
    end

    puts "Clean Step: #{target.cyan}" if @flags.clean_flag
    result = CommandExecutor.new(configuration.get_working, configuration.clean, environment, subs).execute if @flags.clean_flag
    puts "#{'ERROR:'.red} Clean commands for #{target.cyan} returned #{'false'.magenta}" if !result && @flags.clean_flag && @flags.verbose_flag
    return false if !result && @flags.clean_flag

    puts "Build Step: #{target.cyan}"
    result = CommandExecutor.new(configuration.get_working, configuration.build, environment, subs).execute if @flags.build_flag
    puts "#{'ERROR:'.red} Build commands for #{target.cyan} returned #{'false'.magenta}" if !result && @flags.verbose_flag
    puts "#{'SUCCESS:'.green} :: #{target.cyan}" if result
    return false unless result

    if @after_each && !@after_each.empty?
      puts "After Each: #{target.cyan}"
      result = CommandExecutor.new(pwd, @after_each, environment, subs).execute
      puts "#{'ERROR:'.red} After each build commands for #{target.cyan} returned #{'false'.magenta}" if !result && @flags.verbose_flag
      return false unless result
    end
    
    return false unless build_multiple_targets(configuration.get_downstream_targets(@dependency_map), upstream_override || true) if @flags.ensure_downstream

    configuration.built = true
    return true
  end

  def build_multiple_targets targets, upstream_override = false
    return true if targets.empty?
    targets.each do |target|
      matches = /(\.\\)?([^\\\/]+)[\\\/]?$/.match(target)
      target = matches[2] unless matches.nil?

      return false unless build_single_target(target, upstream_override)
    end
    return true
  end

  def self.load_properties flags
    base_filename = "#{Dir.pwd}/deps-#{flags.platform}"
    filenames = [ "#{base_filename}.yaml", "#{base_filename}.yml", "#{base_filename}.json" ]
    filename = filenames.map {|name| File.exist?(name) ? name : nil } .select {|name| !name.nil? } .first

    if filename.nil?
        puts "#{'ERROR:'.red} :: A configuration file must exist for the specified platform: '#{flags.platform.white.bold}'", ''
        flags.print_tasks
    end

    extension = File.extname(filename)

    if '.yml' == extension || '.yaml' == extension then
      begin
        return YAML.load(File.read(filename)), filename[0...-extension.length]
      rescue YAML::SyntaxError => e
          puts "#{'ERROR'.red}: Unable to correctly parse project YAML configuration file: #{filename.white.bold}"
          puts "#{'ERROR'.red}: #{e.message}"
          exit!(-1)
      end
    end

    begin
        return JSON.parse(File.read(filename)), filename[0...-extension.length]
    rescue JSON::JSONError => e
        puts "#{'ERROR'.red}: Unable to correctly parse project JSON configuration file: #{filename.white.bold}"
        puts "#{'ERROR'.red}: #{e.message}"
        exit!(-1)
    end
  end

end



flags = Flags.new(ARGV)

if flags.help_flag then
  flags.print_tasks
end
  
if !flags.has_platform? then
  puts "#{'ERROR'.red} :: Platform parameter must be specified", ''
  flags.print_tasks
end

Dir.chdir(flags.path) do
  builder = DependencyBuilder.new(flags)

  if flags.libraries.empty?
    builder.build_all
  else
    builder.build_list flags.libraries
  end
end
